baseURL = "https://christobit.github.io/"
languageCode = "en-us"
title = "christobit"
theme = "hello-friend"
copyright = ""
paginate = 5

[params]
  subtitle = ""

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
  [[menu.main]]
    identifier = "showcase"
    name = "Showcase"
    url = "/showcase"
